### ISSUE TITLE
just a suggestion.... new idea

### ISSUE THREAD

**Issue by UmairAhmed420** [Chrisvin/LiquidSwipe#2]
your library is awesome .... can you implement one more thing in this library? that is how about when we swipe it detects gesture from where of screen user is swiping so the liquid effects goes there or start from there not from a static position which is mentioned ios library

**Comment by Chrisvin** [comment]
Thanks for the feedback. :) 
I actually did consider something very similar while I was developing the library. I tried making the tip of the wave always match the position of the user's touch, but it didn't turn out as well as I had expected. The initial jumps were too abrupt and the whole animation didn't feel fluid enough.

**Comment by UmairAhmed420** [comment]
still best solution for us ... Thanks for this
